schema_version = "1.0.0"

id = "replacewithcopy"
version = "1.0.0"
name = "Replace With Copy"
tagline = "Batch replace multiple objects with a template"
maintainer = "Brrainz <andreas@pardeike.net>"
type = "add-on"

tags = ["Modeling"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2025 Andreas Pardeike",
]