schema_version = "1.0.0"

id = "replace_with_copy"
version = "1.0.1"
name = "Replace With Copy"
tagline = "Batch replace multiple objects with a template"
maintainer = "Brrainz <andreas@pardeike.net>"
type = "add-on"

tags = ["Modeling"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2025 Andreas Pardeike",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.bat",
  "*.afphoto",
  "*.png",
  "*.zip"
]